services: 
  - type: web
    name: budget-tracker-frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    rootDir: frontend
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://budget-tracker-app-backend-41ib.onrender.com"

  - type: web
    name: budget-tracker-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///instance/budget.db"
