services:
  - type: web
    name: budget-tracker-frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    rootDir: frontend
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://budget-tracker-app-backend.onrender.com"


  - type: web
    name: budget-tracker-frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    rootDir: frontend
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://budget-tracker-app-backend.onrender.com"
